user:
  ivillage_server: "http://www.ivillage.com"
  votigo_server: "https://developerplatform.votigo.com"
  votigo_api_key: "95077f1008caf178109f8c967fab3bda"
  arwen_host: "origin3-www.ivillage.com"
  arwen_user: "astrology"
  arwen_password: "tr7$ar3w"
